switchtolayout;
selectall;
delete;

addrect;
set('name', 'waveguide');
set('x span', 4.8e-7);
set('y span', 2.2e-7);
set('z span', 10e-6);
set('x', 0);
set('y', 0);
set('z', 0);
set('material', 'Si (Silicon) - Palik');

addmesh;
set('name', 'wg_mesh');
set('based on a structure', 1);
set('structure', 'waveguide');

addfde;
set('background material', 'SiO2 (Glass) - Palik');
set('x span', 5e-6);
set('y span', 2.5e-6);
set('x', 0);
set('y', 0);
set('z', 0);
set('x min bc', 'PML');
set('x max bc', 'PML');
set('y min bc', 'PML');
set('y max bc', 'PML');
set('wavelength', 1.55e-6);

function get_imag(){
    findmodes;
    selectmode(1);
    neff_complex = getdata("mode1", "neff");
    return imag(neff_complex);
}

